name: Push
description: Push a Docker image to one or more registries

inputs:
  dockerhub-username:
    required: true
  dockerhub-password:
    required: true
  forgejo-registry-token:
    required: true
  github-token:
    required: true
  refs:
    required: true

runs:
  using: composite
  steps:
    - name: Login to DockerHub
      if: ${{ contains(inputs.refs, 'docker.io') }}
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee  # v4.2.0
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}

    - name: Login to Forgejo Container Registry
      if: ${{ contains(inputs.refs, 'forgejo.treyturner.info') }}
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee  # v4.2.0
      with:
        registry: forgejo.treyturner.info
        username: ${{ github.repository_owner }}
        password: ${{ inputs.forgejo-registry-token }}

    - name: Login to GitHub Container Registry
      if: ${{ contains(inputs.refs, 'ghcr.io') }}
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee  # v4.2.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github-token }}

    - name: Push
      shell: bash -euo pipefail {0}
      run: |
        echo "Pushing images..."
        while IFS= read -r ref; do
          if [ -n "$ref" ]; then
            echo "Pushing $ref"
            docker push "$ref"
          fi
        done <<< "${{ inputs.refs }}"
