name: Push
description: Push a Docker image to one or more registries

inputs:
  dockerhub-username:
    type: string
    required: false
  dockerhub-password:
    type: string
    required: false
  github-token:
    type: string
    required: true
  refs:
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Login to DockerHub
      if: ${{ contains(inputs.refs, 'docker.io') && inputs.dockerhub-username != '' && inputs.dockerhub-password != '' }}
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}

    - name: Login to GitHub Container Registry
      if: ${{ contains(inputs.refs, 'ghcr.io') }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github-token }}

    - name: Push
      shell: bash -euo pipefail {0}
      run: |
        echo "Pushing images..."
        while IFS= read -r ref; do
          if [ -n "$ref" ]; then
            echo "Pushing $ref"
            docker push "$ref"
          fi
        done <<< "${{ inputs.refs }}"
