name: Build and test PR

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build-and-test-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      UPSTREAM_REF: v0.2.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          label: ${{ format('pr{0}', github.event.pull_request.number) }}
          upstream-ref: ${{ env.UPSTREAM_REF }}

      - name: Test
        uses: ./.github/actions/test
        with:
          image-ref: ${{ steps.build.outputs.primary-ref }}
